USE [master]
GO

/****** Object:  Database [wildlife]    Script Date: 11/08/2018 12:07:12 ******/

IF EXISTS (SELECT [name] FROM [master].[sys].[databases] WHERE [name] = N'wildlife')
    DROP DATABASE [wildlife];
GO

/****** Object:  Database [wildlife]    Script Date: 11/08/2018 12:07:12 ******/
CREATE DATABASE [wildlife]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wildlife', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\wildlife.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'wildlife_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\wildlife_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [wildlife] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wildlife].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [wildlife] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [wildlife] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [wildlife] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [wildlife] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [wildlife] SET ARITHABORT OFF 
GO

ALTER DATABASE [wildlife] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [wildlife] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [wildlife] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [wildlife] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [wildlife] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [wildlife] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [wildlife] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [wildlife] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [wildlife] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [wildlife] SET  DISABLE_BROKER 
GO

ALTER DATABASE [wildlife] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [wildlife] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [wildlife] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [wildlife] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [wildlife] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [wildlife] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [wildlife] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [wildlife] SET RECOVERY FULL 
GO

ALTER DATABASE [wildlife] SET  MULTI_USER 
GO

ALTER DATABASE [wildlife] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [wildlife] SET DB_CHAINING OFF 
GO

ALTER DATABASE [wildlife] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [wildlife] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [wildlife] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [wildlife] SET QUERY_STORE = OFF
GO

USE [wildlife]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [wildlife] SET  READ_WRITE 
GO

